### ISSUE TITLE
선택 모드 이슈

### ISSUE THREAD

**Issue by khris** [khris/naver-endic-unofficial#1]
선택 방법을 개선한다
- [ ] #2 오직 한 단어만 선택되었을때 사전을 띄우는 설정 넣기
- [ ] #3 앞뒤로 전치사가 있을때 붙여서 검색할 수 있는 설정 넣기
- [ ] #4 일정 길이 이상의 텍스트가 선택이 되면 사전을 띄우지 않아야 한다
