### ISSUE TITLE
WebExtension으로 모두 이동

### ISSUE THREAD

**Issue by khris** [khris/naver-endic-unofficial#5]
- [x] #6 WE쪽에서 셋팅 메뉴 구현하기
- [x] #8 ContentScript측에서 팝업 띄우기
- [x] #9 설치 혹은 업데이트시 WE쪽에서 확장 사이트 띄우기
- [x] #10 Add-on SDK 에서 WebExtension으로 전환

**Comment by khris** [comment]
다 했다
